OUTDOOR_CAMERA_USER = 'admin'
OUTDOOR_CAMERA_PASSWORD = 'Admin1234'
OUTDOOR_CAMERA_IP = '192.168.0.216/11'

INDOOR_CAMERA_USER = 'admin'
INDOOR_CAMERA_PASSWORD = 'Admin1234'
INDOOR_CAMERA_IP = '192.168.0.216/11'


CAR_REGOGNIZE_CNN_PATH = '/home/michalm/Desktop/POC_GATE/sieci/car_recognize_model.keras'


INDOR_TEST_LINK  = '/home/michalm/Desktop/POC_GATE/wyjazd.mp4'